name: workflow

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v2
      with: { go-version: 1.17.5 }

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with: { terraform_version: 1.1.7 }

    - name: Install Taskfile
      run: curl -sL https://taskfile.dev/install.sh | sh

    - name: Run tests
      run: ./bin/task test
